- name: play level variables
  hosts: local
  connection: local # ansible is connecting to local host
  vars:
    COURSE: ansible
    DURATION: 10HRS
    TRAINER: SIVAKUMAR 
  tasks:
  - name: print the course info
    vars: 
      COURSE: devops
    ansible.builtin.debug:
     msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION}}, Trainer: {{ TRAINER }}"