- name: functions
  hosts: local
  connection: local
  vars:
    name: r.Shiv
    gmail: Rachamalla_shivv@GMAIL.com
    ipaddress: "192.168.0.1"
    technologies: devops, ansible, shell, linux # string
    tags: # dictionary{} == map
     appliction: payment
     environment: dev
    # list[]
    listTags:
    - key: application
      value: payment
    - key: environment
      value: dev
      
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "hi {{ name | default ('ramesh') }}"
  
  #string to list
  - name: string to list
    ansible.builtin.debug:
      msg: "{{ technologies | split(',') }}"
  # map to list 
  - name: map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"
  # list to map
  - name: list to map
    ansible.builtin.debug:
      msg: "{{ listTags | items2dict}}"

  # yaml to json
  - name: read yaml and take it to variable
    ansible.builtin.set_fact:
     student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: yaml to json
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_json }}"
       
  - name: save json output to file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_json }}"

  # uppercase & lower case
  - name: convert to upper case
    ansible.builtin.debug:
        msg: "{{ name | upper }}"

  - name: conert to lowercase
    ansible.builtin.debug:
      msg: "{{ gmail | lower }}"

  
 # pip3.9 install netaddr for ip
  - name: approving ipaddress
    ansible.builtin.debug:
      msg: "{{ ipaddress | ansible.utils.ipv4 }}"
